export const MessageTypeEnum = {
  POSITION_CORRECTION: "POSITION_CORRECTION",
  NEW_PLAYER: "NEW_PLAYER",
  UPDATE_PLAYER_KEYBINDS: "UPDATE_PLAYER_KEYBINDS",
  VERIFY_POSITION: "VERIFY_POSITION",
  REMOVE_PLAYER: "REMOVE_PLAYER",
  DISCONNECT: "DISCONNECT",
  ADD_NEW_PLAYER: "ADD_NEW_PLAYER",
  PLAYER_MOVEMENT: "PLAYER_MOVEMENT",
  AMMO_UPDATE: "AMMO_UPDATE",
  HEALTH_UPDATE: "HEALTH_UPDATE",
} as const;

export type MessageType = keyof typeof MessageTypeEnum;