export const MessageTypeEnum = {
    // Game events
    POSITION_CORRECTION: "POSITION_CORRECTION",
    ADD_NEW_PLAYER: "ADD_NEW_PLAYER",
    NEW_PLAYER: "NEW_PLAYER",
    UPDATE_PLAYER: "UPDATE_PLAYER",
    REMOVE_PLAYER: "REMOVE_PLAYER",
    UPDATE_PLAYER_KEYBINDS: "UPDATE_PLAYER_KEYBINDS",
    VERIFY_POSITION: "VERIFY_POSITION",
    DISCONNECT: "DISCONNECT",
    // Player
    PLAYER_MOVEMENT: "PLAYER_MOVEMENT",
    AMMO_UPDATE: "AMMO_UPDATE",
    HEALTH_UPDATE: "HEALTH_UPDATE",
    // Chat messages
    SEND_CHAT_MESSAGE: "SEND_CHAT_MESSAGE",
    SEND_PRIVATE_MESSAGE: "SEND_PRIVATE_MESSAGE",
    GET_CHAT_MESSAGES: "GET_CHAT_MESSAGES",
    GET_PRIVATE_MESSAGES: "GET_PRIVATE_MESSAGES",
    COMMAND_RESPONSE: "COMMAND_RESPONSE",
    // Login/Registration
    LOGIN: "LOGIN",
    REGISTER: "REGISTER",
    LOGIN_RESPONSE: "LOGIN_RESPONSE",
    REGISTER_RESPONSE: "REGISTER_RESPONSE",
};
