# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@latest
        with:
          deno-version: v1.x
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        run: deno check **/*.ts --allow-import
        
      - name: Run tests
        run: |
          deno test -A || if [ $? -eq 1 ]; then 
            if grep -q "No test modules found" <<< "$(deno test -A 2>&1)"; then
              echo "No tests found, but that's OK!"
              exit 0
            else
              exit 1
            fi
          fi
