name: Deploy Backend
on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Create and switch to deploy branch
        run: |
          git checkout -b deploy-back
      - name: Restructure repository
        run: |
          # Remove client directory
          rm -rf client

          # Keep everything else intact
          echo "Removed client folder"
      - name: Add deployment files
        run: |
          # Create Procfile with updated permissions for backend
          cat > Procfile << 'EOF'
          web: ./.heroku/bin/deno run --allow-net --allow-read --allow-import --allow-write server/back_server.ts $PORT
          EOF

          # Create .buildpacks
          cat > .buildpacks << 'EOF'
          https://github.com/chibat/heroku-buildpack-deno.git
          EOF

          # Create Dockerfile with updated permissions for backend
          cat > Dockerfile << 'EOF'
          FROM denoland/deno:latest
          WORKDIR /app

          COPY --from=builder /app .

          CMD ["deno", "run", "--allow-read", "--allow-net", "--allow-env", "--allow-import", "--allow-write", "server/back_server.ts"]
          EOF

          echo "Deployment files created successfully"
      - name: Update server configuration
        run: |
          # Remove empty cert and key properties from options object
          sed -i 's/options = {\n    port: Number(Deno.args\[0\]),\n    secure: true,\n    cert: "",\n    key: "",\n  };/options = {\n    port: Number(Deno.args[0]),\n    secure: true,\n  };/g' server/back_server.ts

          echo "Server configuration updated"
      - name: Replace URLs in files
        run: |
          # Replace localhost:8080 by webwarfare.cluster-ig3.igpolytech.fr
          find . -type f -not -path "*/node_modules/*" -not -path "*/\.git/*" -exec sed -i 's/localhost:8080/webwarfare.cluster-ig3.igpolytech.fr/g' {} \;

          # Replace localhost:3000 by webwarfare-back.cluster-ig3.igpolytech.fr
          find . -type f -not -path "*/node_modules/*" -not -path "*/\.git/*" -exec sed -i 's/localhost:3000/webwarfare-back.cluster-ig3.igpolytech.fr/g' {} \;

          echo "URL replacements completed"
      - name: Commit changes
        run: |
          git add .
          git commit -m "Deploy backend: Client folder removed, URLs updated, and deployment files added"
      - name: Push to deploy-back branch
        run: |
          git push origin deploy-back --force

          echo "Deployment branch pushed successfully. You can now deploy to Dokku."
